AllCops:
  TargetRubyVersion: 3.0.1
  NewCops: enable
  Exclude:
    - '**/vendor/**/*'
    - '**/schema.rb'
    - '**/db/migrate/**'
    - '**/bin/*'
    - '**/config/**/*'
    - '**/config/**/8'


Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/YodaCondition:
  Enabled: false
